### PR TITLE
Fix some minor things of `calling-c-from-common-lisp`

### PR DESCRIPTION
**Pull request by muyinliu**

### CODE REVIEW

**Comment by timmyjose** [comment]
@muyinliu Reviewed. Please go ahead and merge the changes in! If you don't have access permissions, please let me know! :-)

**Comment by muyinliu** [comment]
You have to click the "Merge pull request" button on current page yourself.

**Comment by timmyjose** [comment]
> You have to click the "Merge pull request" button on current page yourself.
> 
> Note: I don't have the write access to this repo.

Hey, I have added you as a collaborator for this repo. Please go ahead and merge the issue - I want to maintain provenance of authorship for the PRs! :-)

**Comment by muyinliu** [comment]
Merged. Thanks.

**Pull request merged**
